# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 12:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 12, 47, 13, 670712, tzinfo=utc)),
        ),
    ]
